### ISSUE TITLE
[Bug] dead link in call for feedback link at the end of the course

### ISSUE THREAD

**Issue by ArnoudBM** [skills/deploy-to-azure#22]
**Describe the bug**
In the detail panel Finish of the readme.md of the course is a call for feedback:

What's next?
[We'd love to hear what you thought of this course](https://github.com/skills/continuous-delivery-azure/blob/main/TBD-feedback-link).
The 'skills/continuous-delivery-azure' repository doesn't contain the 'TBD-feedback-link' path in 'main'.  

**To Reproduce**
1. Go to 'https://github.com/skills/continuous-delivery-azure'
2. In the readme on this page, scroll down to 'Finish' and click it
3. Scroll down to 'What's next'
4. Click the first link: 'We'd love to hear what you thought of this course.'
5. See error

**Expected behavior**
The link should lead to the github skills evaluation page or https://github.com/skills/.github/discussions

**Device information**
 - All platforms and browsers
 - [88b4580](https://github.com/skills/continuous-delivery-azure/commit/88b45809ea99abb1bf55ed2ed379303913a42b4a)
[25 days ago](https://github.com/skills/continuous-delivery-azure/commit/88b45809ea99abb1bf55ed2ed379303913a42b4a)
Git stats

**Comment by rffontenelle** [comment]
Fixed in #58
