### ISSUE TITLE
[Bug] Step missing for Activity 1: Add triggers to production deployment workflow after steps 6

### ISSUE THREAD

**Issue by wongcyrus** [skills/deploy-to-azure#30]
**Describe the bug**
Redme.md Step missing for Activity 1: Add triggers to production deployment workflow after steps 6.

**To Reproduce**
Please read the instructions and it will jump to the end and lack of information to complete the task.
**Expected behavior**
Some more intermediate steps with instruction.

**Comment by rffontenelle** [comment]
Deployment is triggered by merging the pull request, which makes the new commit to main branch to start the workflow as per [step 5](https://github.com/skills/deploy-to-azure/blob/main/.github/steps/5-deploy-to-prod-environment.md) info.

**Comment by hectorsector** [comment]
Thanks for the feedback, @wongcyrus!
