### ISSUE TITLE
[Bug] AZURE_CREDENTIALS are in instructions but never created

### ISSUE THREAD

**Issue by hectorsector** [skills/deploy-to-azure#84]
### Summary

A [change](https://github.com/skills/deploy-to-azure/pull/78/files#diff-17dca27e6e7141b93192d30c8d0b20414d8cd3040f55fd0084963c691b57bb77L65-R70) we recently accepted removed the creation of a secret called `AZURE_CREDENTIALS`. That secret is still utilized in one of the workflows we ask the learner to create:

https://github.com/skills/deploy-to-azure/blob/ae0c3ff6062a55a4106a388ced6e6c96f0d4eac1/.github/steps/3-spinup-environment.md?plain=1#L64-L67

### How to reproduce

1. Take the course
2. At step 3, you'll see the workflow referenced. It will immediately fail on the login action.
3. The course will continue to move forward eventually, but no actual Azure workflow ran.

**Comment by bronthulke** [comment]
Yep I've just experienced the same issue.

For those who are struggling to get past this, this is what I did:

1. Delete the service principal created previously and recreate it, but this time in the CLI include the argument `--json-auth`
2. Add an Actions Secret in GitHub for AZURE_CREDENTIALS with the JSON returned from the above
3. Update the existing secrets created for AZURE_TENANT_ID and AZURE_CLIENT_ID with the values out of JSON
4. Go to Actions and into the failed run, and click "Rerun all jobs" (it will skill skip the Destroy job)

This worked for me, and then I was able to continue with the exercise.
